name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} npm test

  # test action works running with run id
  test-run-id:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        repository: channyein87/workflow-duration-action
        run_id: 2395414061
        github_token: ${{ secrets.GITHUB_TOKEN }}

  # test action works running with workflow
  test-workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        repository: channyein87/workflow-duration-action
        workflow: workflow-run.yml
        github_token: ${{ secrets.GITHUB_TOKEN }}
